### PR TITLE
Fix for XMLValidator is using system out to print errors

### LINKED ISSUE #7: XMLValidator is using system out to print errors.
Replace with the logging framework used.

refer to how other classes are handling Logging. e.g. org.kik.bot.core.KikClient

### PR DESCRIPTION
**Pull request by priyankalakhe**
Fixed https://github.com/iservecharlie/LynxKikApi/issues/7

### CODE REVIEW

File: src/main/java/org/kik/bot/core/validator/XmlValidator.java [hunk 1]
```diff
@@ -59,12 +61,11 @@ private boolean parseDataAsXml(String data) {
             dBuilder.parse(input);
             validXml = true;
         } catch (UnsupportedEncodingException | ParserConfigurationException e) {
-            e.printStackTrace();
+            LOGGER.error("Exception seen for " + data, e);
```
Comment (iservecharlie) [inline src/main/java/org/kik/bot/core/validator/XmlValidator.java]: I think as a default if the exception is provided as the second argument in the logger, it would display the class of error it that was passed. Specifying the class of error in the message might be redundant.

Comment (priyankalakhe) [reply src/main/java/org/kik/bot/core/validator/XmlValidator.java]: @iservecharlie - apologies for the delay. 
Your suggestion makes sense. 
Let me change out the log message. 
For now, keeping it the same message `Exception seen for ` for the three catch clauses. 

Changes on https://github.com/iservecharlie/LynxKikApi/pull/8/files/1fbaf4be6f24baa874b001fb4e6b4e300e5c15af..45a73bd8a957ad34548b1b6a21f7d00d69e0fb2d

If you want to merge the catch clauses in, I can do that in a successive PR.
